import { promisify } from "node:util";
import { execFile as execFileCallback } from "node:child_process";
import fs from "node:fs";
import fsPromises from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import type {
  BatchDetail,
  BatchListingSettings,
  BatchSummary,
  DetectionRecord,
  ExportRecord,
  ReviewItem,
  UploadRecord,
  VideoDebugFrame,
  VideoDebugUpload,
} from "./types";
import { resolveProjectRoot } from "./project-paths";

const execFile = promisify(execFileCallback);

function resolveDatabasePath() {
  const cwd = process.cwd();
  const candidates = [
    path.join(cwd, "prisma", "dev.db"),
    path.resolve(cwd, "..", "..", "prisma", "dev.db"),
  ];

  return candidates.find((candidate) => fs.existsSync(candidate)) ?? candidates[0];
}

const DATABASE_PATH = resolveDatabasePath();

async function queryRows<T>(sql: string): Promise<T[]> {
  const { stdout } = await execFile("sqlite3", ["-json", DATABASE_PATH, sql], {
    maxBuffer: 1024 * 1024 * 64,
  });
  const trimmed = stdout.trim();
  return trimmed ? (JSON.parse(trimmed) as T[]) : [];
}

async function runStatement(sql: string): Promise<void> {
  await execFile("sqlite3", [DATABASE_PATH, sql]);
}

function escapeSqliteString(value: string) {
  return value.replace(/'/g, "''");
}

type SqlBatchSummary = {
  id: string;
  name: string;
  sellerLabel: string;
  intakeMode: "video" | "images";
  status: BatchSummary["status"];
  itemCount: number;
  reviewCount: number;
  exportReady: number;
  updatedAt: string;
};

type SqlListingSettings = {
  location: string | null;
  shippingType: string | null;
  shippingCost: string | null;
  returnsAcceptedOption: string | null;
  returnsWithinOption: string | null;
  refundOption: string | null;
  shippingCostPaidByOption: string | null;
  dispatchTimeMax: number | null;
  cardConditionDescriptor: string | null;
  descriptionTemplate: string | null;
};

type SqlUpload = {
  id: string;
  fileName: string;
  storageKey: string | null;
  type: "video" | "images";
  status: UploadRecord["status"];
  durationSeconds: number | null;
  imageCount: number | null;
  uploadedAt: string;
};

type SqlDetection = {
  id: string;
  frameLabel: string;
  cardName: string | null;
  setName: string | null;
  cardNumber: string | null;
  rarity: string | null;
  confidence: number;
  status: DetectionRecord["status"];
  notes: string | null;
  titleOverride: string | null;
  priceOverride: string | null;
  quantityOverride: number | null;
  conditionOverride: string | null;
  excludeFromExport: number;
  resolvedByReview: number;
};

type SqlReview = {
  id: string;
  frameLabel: string;
  storageKey: string | null;
  suggestedMatch: string;
  alternateMatches: string;
  reason: string;
};

type SqlExportRun = {
  id: string;
  format: string;
  status: string;
  filePath: string | null;
  createdAt: string;
};

type ExportableRow = {
  detectionId: string;
  sourceLabel: string;
  cardName: string | null;
  setName: string | null;
  setCode: string | null;
  externalSetId: string | null;
  cardNumber: string | null;
  rarity: string | null;
  imageLargeUrl: string | null;
  imageSmallUrl: string | null;
  titleOverride: string | null;
  priceOverride: string | null;
  quantityOverride: number | null;
  conditionOverride: string | null;
  excludeFromExport: number;
};

function formatDuration(value: number | null) {
  if (!value) {
    return undefined;
  }

  return `${Math.floor(value / 60).toString().padStart(2, "0")}:${(value % 60)
    .toString()
    .padStart(2, "0")}`;
}

function buildListingSettings(row: SqlListingSettings): BatchListingSettings {
  return {
    location: row.location ?? "Toronto, Ontario",
    shippingType: row.shippingType === "Free" ? "Free" : "Flat",
    shippingCost: row.shippingCost ?? "1.99",
    returnsAcceptedOption:
      row.returnsAcceptedOption === "ReturnsNotAccepted" ? "ReturnsNotAccepted" : "ReturnsAccepted",
    returnsWithinOption: row.returnsWithinOption ?? "Days_30",
    refundOption: row.refundOption ?? "MoneyBack",
    shippingCostPaidByOption: row.shippingCostPaidByOption === "Seller" ? "Seller" : "Buyer",
    dispatchTimeMax: String(row.dispatchTimeMax ?? 3),
    cardConditionDescriptor: row.cardConditionDescriptor ?? "400010",
    descriptionTemplate:
      row.descriptionTemplate ??
      "{card_name} from {set_name}. Card number: {card_number}. Rarity: {rarity}. Generated by TCG Listing Platform draft export.",
  };
}

function buildCatalogFallbackImageUrl(externalSetId: string | null, cardNumber: string | null) {
  if (!externalSetId || !cardNumber) {
    return undefined;
  }

  const collectorNumber = cardNumber.split("/")[0];
  return `https://images.pokemontcg.io/${externalSetId}/${collectorNumber}_hires.png`;
}

function parseReviewMatchLabel(label: string) {
  const trimmed = label.trim();
  const lastSpaceIndex = trimmed.lastIndexOf(" ");
  const cardNumber = lastSpaceIndex > 0 ? trimmed.slice(lastSpaceIndex + 1).trim() : "";
  const name = lastSpaceIndex > 0 ? trimmed.slice(0, lastSpaceIndex).trim() : trimmed;

  if (!name || !cardNumber) {
    return null;
  }

  return { name, cardNumber };
}

async function getCatalogImageUrlsForReviewMatches(matchLabels: string[]) {
  const parsedMatches = matchLabels
    .map(parseReviewMatchLabel)
    .filter((value): value is NonNullable<typeof value> => Boolean(value));

  if (parsedMatches.length === 0) {
    return {};
  }

  const whereClauses = parsedMatches
    .map(
      ({ name, cardNumber }) =>
        `(CatalogCard.name = '${escapeSqliteString(name)}' AND CatalogCard.cardNumber = '${escapeSqliteString(cardNumber)}')`,
    )
    .join(" OR ");

  const rows = await queryRows<{
    name: string;
    cardNumber: string;
    externalSetId: string | null;
    imageLargeUrl: string | null;
    imageSmallUrl: string | null;
  }>(`
    SELECT
      CatalogCard.name,
      CatalogCard.cardNumber,
      CatalogSet.externalSetId,
      CatalogCard.imageLargeUrl,
      CatalogCard.imageSmallUrl
    FROM CatalogCard
    LEFT JOIN CatalogSet ON CatalogSet.id = CatalogCard.setId
    WHERE ${whereClauses};
  `);

  return Object.fromEntries(
    rows
      .map((row) => [
        `${row.name} ${row.cardNumber}`,
        row.imageLargeUrl ||
          row.imageSmallUrl ||
          buildCatalogFallbackImageUrl(row.externalSetId, row.cardNumber),
      ])
      .filter((entry): entry is [string, string] => Boolean(entry[1])),
  );
}

export async function listSqliteBatches(): Promise<BatchSummary[]> {
  const rows = await queryRows<SqlBatchSummary>(`
    SELECT
      id,
      name,
      sellerLabel,
      CASE intakeMode WHEN 'VIDEO' THEN 'video' ELSE 'images' END AS intakeMode,
      LOWER(status) AS status,
      itemCount,
      reviewCount,
      exportReady,
      strftime('%Y-%m-%d %H:%M', updatedAt) AS updatedAt
    FROM Batch
    ORDER BY updatedAt DESC;
  `);

  return rows.map((row) => ({
    id: row.id,
    name: row.name,
    sellerLabel: row.sellerLabel,
    game: "Pokemon",
    intakeMode: row.intakeMode,
    status: row.status,
    itemCount: row.itemCount,
    reviewCount: row.reviewCount,
    exportReady: Boolean(row.exportReady),
    updatedAt: row.updatedAt,
  }));
}

export async function getSqliteBatchDetail(batchId: string): Promise<BatchDetail | null> {
  const batches = await queryRows<SqlBatchSummary & SqlListingSettings>(`
    SELECT
      id,
      name,
      sellerLabel,
      CASE intakeMode WHEN 'VIDEO' THEN 'video' ELSE 'images' END AS intakeMode,
      LOWER(status) AS status,
      itemCount,
      reviewCount,
      exportReady,
      location,
      shippingType,
      shippingCost,
      returnsAcceptedOption,
      returnsWithinOption,
      refundOption,
      shippingCostPaidByOption,
      dispatchTimeMax,
      cardConditionDescriptor,
      descriptionTemplate,
      strftime('%Y-%m-%d %H:%M', updatedAt) AS updatedAt
    FROM Batch
    WHERE id = '${batchId}';
  `);

  const batch = batches[0];

  if (!batch) {
    return null;
  }

  const uploads = await queryRows<SqlUpload>(`
    SELECT
      id,
      fileName,
      storageKey,
      CASE kind WHEN 'VIDEO' THEN 'video' ELSE 'images' END AS type,
      LOWER(status) AS status,
      durationSeconds,
      imageCount,
      strftime('%Y-%m-%d %H:%M', uploadedAt) AS uploadedAt
    FROM Upload
    WHERE batchId = '${batchId}'
    ORDER BY uploadedAt ASC;
  `);

  const detections = await queryRows<SqlDetection>(`
    SELECT
      id,
      sourceLabel AS frameLabel,
      cardName,
      setName,
      cardNumber,
      rarity,
      confidence,
      LOWER(status) AS status,
      notes,
      titleOverride,
      priceOverride,
      quantityOverride,
      conditionOverride,
      excludeFromExport,
      EXISTS(
        SELECT 1
        FROM ReviewItem
        WHERE ReviewItem.detectionId = Detection.id
          AND ReviewItem.state = 'RESOLVED'
      ) AS resolvedByReview
    FROM Detection
    WHERE batchId = '${batchId}'
    ORDER BY createdAt ASC;
  `);

  const reviewQueue = await queryRows<SqlReview>(`
    SELECT
      ReviewItem.id,
      Detection.sourceLabel AS frameLabel,
      Upload.storageKey,
      ReviewItem.suggestedMatch,
      ReviewItem.alternateMatches,
      ReviewItem.reason
    FROM ReviewItem
    INNER JOIN Detection ON Detection.id = ReviewItem.detectionId
    LEFT JOIN Upload ON Upload.id = Detection.uploadId
    WHERE ReviewItem.batchId = '${batchId}'
    ORDER BY ReviewItem.createdAt ASC;
  `);

  const exportRuns = await queryRows<SqlExportRun>(`
    SELECT
      id,
      format,
      status,
      filePath,
      strftime('%Y-%m-%d %H:%M', createdAt) AS createdAt
    FROM ExportRun
    WHERE batchId = '${batchId}'
    ORDER BY createdAt DESC;
  `);

  const reviewMatchImageUrls = await getCatalogImageUrlsForReviewMatches(
    reviewQueue.flatMap((item) => [
      item.suggestedMatch,
      ...item.alternateMatches.split("||").map((entry) => entry.trim()),
    ]),
  );

  return {
    id: batch.id,
    name: batch.name,
    sellerLabel: batch.sellerLabel,
    game: "Pokemon",
    intakeMode: batch.intakeMode,
    status: batch.status,
    itemCount: batch.itemCount,
    reviewCount: batch.reviewCount,
    exportReady: Boolean(batch.exportReady),
    updatedAt: batch.updatedAt,
    listingSettings: buildListingSettings(batch),
    uploads: uploads.map(
      (upload): UploadRecord => ({
        id: upload.id,
        fileName: upload.fileName,
        type: upload.type,
        status: upload.status,
        durationLabel: formatDuration(upload.durationSeconds),
        imageCount: upload.imageCount ?? undefined,
        uploadedAt: upload.uploadedAt,
      }),
    ),
    detections: detections.map(
      (detection): DetectionRecord => ({
        id: detection.id,
        frameLabel: detection.frameLabel,
        cardName: detection.cardName ?? "Unknown card",
        setName: detection.setName ?? "Unknown set",
        cardNumber: detection.cardNumber ?? "-",
        rarity: detection.rarity ?? "-",
        confidence: detection.confidence,
        status: detection.status,
        notes: detection.notes ?? undefined,
        titleOverride: detection.titleOverride ?? undefined,
        priceOverride: detection.priceOverride ?? undefined,
        quantityOverride:
          detection.quantityOverride !== null ? String(detection.quantityOverride) : undefined,
        conditionOverride: detection.conditionOverride ?? undefined,
        excludeFromExport: Boolean(detection.excludeFromExport),
        resolvedByReview: Boolean(detection.resolvedByReview),
      }),
    ),
    reviewQueue: reviewQueue.map(
      (item): ReviewItem => ({
        id: item.id,
        frameLabel: item.frameLabel,
        frameImageUrl: item.storageKey
          ? `/api/local-media?path=${encodeURIComponent(
              path.join(buildFrameDirectoryFromStorageKey(item.storageKey), `${item.frameLabel.replace(" ", "-").toLowerCase()}.png`),
            )}`
          : undefined,
        frameCropImageUrl: item.storageKey
          ? `/api/local-media?path=${encodeURIComponent(
              path.join(
                buildOcrDirectoryFromStorageKey(item.storageKey),
                `${item.frameLabel.replace(" ", "-").toLowerCase()}-card.png`,
              ),
            )}`
          : undefined,
        suggestedMatch: item.suggestedMatch,
        suggestedMatchImageUrl: reviewMatchImageUrls[item.suggestedMatch],
        alternateMatches: item.alternateMatches
          .split("||")
          .map((entry) => entry.trim())
          .filter(Boolean),
        alternateMatchImageUrls: Object.fromEntries(
          item.alternateMatches
            .split("||")
            .map((entry) => entry.trim())
            .filter(Boolean)
            .map((match) => [match, reviewMatchImageUrls[match]])
            .filter((entry): entry is [string, string] => Boolean(entry[1])),
        ),
        reason: item.reason,
      }),
    ),
    exportRuns: exportRuns.map(
      (run): ExportRecord => ({
        id: run.id,
        format: run.format,
        status: run.status,
        filePath: run.filePath ?? undefined,
        createdAt: run.createdAt,
      }),
    ),
  };
}

type SqlVideoDebugDetection = {
  uploadId: string;
  frameLabel: string;
  cardName: string | null;
  setName: string | null;
  cardNumber: string | null;
  rarity: string | null;
  confidence: number;
  status: DetectionRecord["status"];
  notes: string | null;
  resolvedByReview: number;
  externalSetId: string | null;
  imageLargeUrl: string | null;
  imageSmallUrl: string | null;
};

function buildFrameDirectoryFromStorageKey(storageKey: string) {
  const parsed = path.parse(storageKey);
  return path.join(parsed.dir, `${parsed.name}-frames`);
}

function buildOcrDirectoryFromStorageKey(storageKey: string) {
  const parsed = path.parse(storageKey);
  return path.join(parsed.dir, `${parsed.name}-ocr`);
}

export async function getSqliteBatchVideoDebug(batchId: string): Promise<VideoDebugUpload[]> {
  const safeBatchId = escapeSqliteString(batchId);
  const projectRoot = resolveProjectRoot();

  const uploads = await queryRows<SqlUpload>(`
    SELECT
      id,
      fileName,
      storageKey,
      CASE kind WHEN 'VIDEO' THEN 'video' ELSE 'images' END AS type,
      LOWER(status) AS status,
      durationSeconds,
      imageCount,
      strftime('%Y-%m-%d %H:%M', uploadedAt) AS uploadedAt
    FROM Upload
    WHERE batchId = '${safeBatchId}'
      AND kind = 'VIDEO'
    ORDER BY uploadedAt ASC;
  `);

  if (uploads.length === 0) {
    return [];
  }

  const detections = await queryRows<SqlVideoDebugDetection>(`
    SELECT
      Detection.uploadId,
      Detection.sourceLabel AS frameLabel,
      Detection.cardName,
      Detection.setName,
      Detection.cardNumber,
      Detection.rarity,
      Detection.confidence,
      LOWER(Detection.status) AS status,
      Detection.notes,
      EXISTS(
        SELECT 1
        FROM ReviewItem
        WHERE ReviewItem.detectionId = Detection.id
          AND ReviewItem.state = 'RESOLVED'
      ) AS resolvedByReview,
      COALESCE(ResolvedSet.externalSetId, CatalogSet.externalSetId) AS externalSetId,
      COALESCE(ResolvedCard.imageLargeUrl, CatalogCard.imageLargeUrl) AS imageLargeUrl,
      COALESCE(ResolvedCard.imageSmallUrl, CatalogCard.imageSmallUrl) AS imageSmallUrl
    FROM Detection
    LEFT JOIN ReviewItem AS ResolvedReview
      ON ResolvedReview.detectionId = Detection.id
      AND ResolvedReview.state = 'RESOLVED'
    LEFT JOIN CatalogCard ON CatalogCard.id = Detection.suggestedCardId
    LEFT JOIN CatalogCard AS ResolvedCard ON ResolvedCard.id = ResolvedReview.resolvedCardId
    LEFT JOIN CatalogSet ON CatalogSet.id = CatalogCard.setId
    LEFT JOIN CatalogSet AS ResolvedSet ON ResolvedSet.id = ResolvedCard.setId
    WHERE Detection.batchId = '${safeBatchId}'
      AND Detection.uploadId IS NOT NULL
    ORDER BY Detection.createdAt ASC;
  `);

  const detectionsByUpload = new Map<string, Map<string, SqlVideoDebugDetection>>();

  for (const detection of detections) {
    const uploadDetections = detectionsByUpload.get(detection.uploadId) ?? new Map<string, SqlVideoDebugDetection>();
    uploadDetections.set(detection.frameLabel, detection);
    detectionsByUpload.set(detection.uploadId, uploadDetections);
  }

  const debugUploads = await Promise.all(
    uploads.map(async (upload): Promise<VideoDebugUpload> => {
      const frames: VideoDebugFrame[] = [];
      const uploadDetections = detectionsByUpload.get(upload.id) ?? new Map<string, SqlVideoDebugDetection>();
      const storageKey = upload.storageKey ?? "";

      if (storageKey) {
        const frameDirectory = buildFrameDirectoryFromStorageKey(storageKey);
        const absoluteFrameDirectory = path.join(projectRoot, frameDirectory);
        const ocrDirectory = buildOcrDirectoryFromStorageKey(storageKey);
        const absoluteOcrDirectory = path.join(projectRoot, ocrDirectory);

        try {
          const frameFiles = (await fsPromises.readdir(absoluteFrameDirectory))
            .filter((entry) => entry.endsWith(".png"))
            .sort((left, right) => left.localeCompare(right));

          for (const frameFile of frameFiles) {
            const relativeFramePath = path.join(frameDirectory, frameFile);
            const frameBaseName = path.parse(frameFile).name;
            const frameOrdinal = frameBaseName.replace(/^frame-/, "");
            const frameLabel = `Frame ${frameOrdinal}`;
            const detection = uploadDetections.get(frameLabel);
            const referenceImageUrl =
              detection?.imageLargeUrl ||
              detection?.imageSmallUrl ||
              buildCatalogFallbackImageUrl(detection?.externalSetId ?? null, detection?.cardNumber ?? null);
            const cardCropRelativePath = path.join(ocrDirectory, `frame-${frameOrdinal}-card.png`);
            const topCropRelativePath = path.join(ocrDirectory, `frame-${frameOrdinal}-top.png`);
            const bottomCropRelativePath = path.join(ocrDirectory, `frame-${frameOrdinal}-bottom.png`);
            const [hasCardCrop, hasTopCrop, hasBottomCrop] = await Promise.all([
              fsPromises
                .access(path.join(absoluteOcrDirectory, `frame-${frameOrdinal}-card.png`))
                .then(() => true)
                .catch(() => false),
              fsPromises
                .access(path.join(absoluteOcrDirectory, `frame-${frameOrdinal}-top.png`))
                .then(() => true)
                .catch(() => false),
              fsPromises
                .access(path.join(absoluteOcrDirectory, `frame-${frameOrdinal}-bottom.png`))
                .then(() => true)
                .catch(() => false),
            ]);

            frames.push({
              frameLabel,
              frameImageUrl: `/api/local-media?path=${encodeURIComponent(relativeFramePath)}`,
              cardCropImageUrl: hasCardCrop
                ? `/api/local-media?path=${encodeURIComponent(cardCropRelativePath)}`
                : undefined,
              ocrTopImageUrl: hasTopCrop
                ? `/api/local-media?path=${encodeURIComponent(topCropRelativePath)}`
                : undefined,
              ocrBottomImageUrl: hasBottomCrop
                ? `/api/local-media?path=${encodeURIComponent(bottomCropRelativePath)}`
                : undefined,
              matchedCardName: detection?.cardName ?? undefined,
              matchedSetName: detection?.setName ?? undefined,
              matchedCardNumber: detection?.cardNumber ?? undefined,
              matchedRarity: detection?.rarity ?? undefined,
              confidence: detection?.confidence,
              status: detection?.status,
              notes: detection?.notes ?? undefined,
              referenceImageUrl,
              referenceImageLabel:
                detection?.cardName && detection?.cardNumber
                  ? `${detection.cardName} ${detection.cardNumber}`
                  : undefined,
              resolvedByReview: Boolean(detection?.resolvedByReview),
            });
          }
        } catch {
          // Ignore missing frame directories and return an empty frame list.
        }
      }

      return {
        uploadId: upload.id,
        fileName: upload.fileName,
        uploadedAt: upload.uploadedAt,
        durationLabel: formatDuration(upload.durationSeconds),
        frameCount: frames.length,
        matchedFrameCount: frames.filter((frame) => Boolean(frame.matchedCardName)).length,
        frames,
      };
    }),
  );

  return debugUploads;
}

type CreateBatchInput = {
  name: string;
  sellerLabel: string;
  intakeMode: "video" | "images";
};

export async function createSqliteBatch(input: CreateBatchInput): Promise<string> {
  const id = `batch-${crypto.randomUUID()}`;
  const name = escapeSqliteString(input.name);
  const sellerLabel = escapeSqliteString(input.sellerLabel);
  const intakeMode = input.intakeMode === "video" ? "VIDEO" : "IMAGES";

  await runStatement(`
    INSERT INTO Batch (
      id,
      name,
      sellerLabel,
      game,
      intakeMode,
      status,
      itemCount,
      reviewCount,
      exportReady,
      location,
      shippingType,
      shippingCost,
      returnsAcceptedOption,
      returnsWithinOption,
      refundOption,
      shippingCostPaidByOption,
      dispatchTimeMax,
      cardConditionDescriptor,
      descriptionTemplate,
      createdAt,
      updatedAt
    ) VALUES (
      '${id}',
      '${name}',
      '${sellerLabel}',
      'POKEMON',
      '${intakeMode}',
      'DRAFT',
      0,
      0,
      0,
      'Toronto, Ontario',
      'Flat',
      '1.99',
      'ReturnsAccepted',
      'Days_30',
      'MoneyBack',
      'Buyer',
      3,
      '400010',
      '{card_name} from {set_name}. Card number: {card_number}. Rarity: {rarity}. Generated by TCG Listing Platform draft export.',
      CURRENT_TIMESTAMP,
      CURRENT_TIMESTAMP
    );
  `);

  return id;
}

type CreateUploadInput = {
  batchId: string;
  fileName: string;
  storageKey: string;
  kind: "video" | "images";
  durationSeconds?: number;
  imageCount?: number;
};

export async function createSqliteUpload(input: CreateUploadInput): Promise<string> {
  const id = `upload-${crypto.randomUUID()}`;
  const fileName = escapeSqliteString(input.fileName);
  const storageKey = escapeSqliteString(input.storageKey);
  const kind = input.kind === "video" ? "VIDEO" : "IMAGES";
  const batchId = escapeSqliteString(input.batchId);

  await runStatement(`
    INSERT INTO Upload (
      id,
      batchId,
      kind,
      fileName,
      storageKey,
      status,
      durationSeconds,
      imageCount,
      uploadedAt
    ) VALUES (
      '${id}',
      '${batchId}',
      '${kind}',
      '${fileName}',
      '${storageKey}',
      'UPLOADED',
      ${typeof input.durationSeconds === "number" ? input.durationSeconds : "NULL"},
      ${typeof input.imageCount === "number" ? input.imageCount : "NULL"},
      CURRENT_TIMESTAMP
    );
  `);

  await runStatement(`
    UPDATE Batch
    SET
      intakeMode = '${kind}',
      status = 'PROCESSING',
      exportReady = 0,
      updatedAt = CURRENT_TIMESTAMP
    WHERE id = '${batchId}';
  `);

  return id;
}

type DetectionTemplate = {
  sourceLabel?: string;
  cardName: string;
  setName: string;
  cardNumber: string;
  rarity: string;
  confidence: number;
  status: "MATCHED" | "NEEDS_REVIEW";
  notes?: string;
  review?: {
    suggestedMatch: string;
    alternateMatches: string[];
    reason: string;
  };
};

const PROCESSING_TEMPLATES: Record<"video" | "images", DetectionTemplate[]> = {
  video: [
    {
      cardName: "Pikachu ex",
      setName: "Surging Sparks",
      cardNumber: "057/191",
      rarity: "Double Rare",
      confidence: 0.98,
      status: "MATCHED",
    },
    {
      cardName: "Buddy-Buddy Poffin",
      setName: "Temporal Forces",
      cardNumber: "144/162",
      rarity: "Uncommon",
      confidence: 0.68,
      status: "NEEDS_REVIEW",
      notes: "Simulated glare conflict near collector number.",
      review: {
        suggestedMatch: "Buddy-Buddy Poffin 144/162",
        alternateMatches: ["Buddy-Buddy Poffin 223/162", "Counter Catcher 160/182"],
        reason: "Confidence is below threshold and needs seller confirmation.",
      },
    },
    {
      cardName: "Charizard ex",
      setName: "Obsidian Flames",
      cardNumber: "125/197",
      rarity: "Double Rare",
      confidence: 0.96,
      status: "MATCHED",
    },
  ],
  images: [
    {
      cardName: "Nest Ball",
      setName: "Paldean Fates",
      cardNumber: "084/091",
      rarity: "Shiny Rare",
      confidence: 0.94,
      status: "MATCHED",
    },
    {
      cardName: "Iono",
      setName: "Paldea Evolved",
      cardNumber: "185/193",
      rarity: "Special Illustration Rare",
      confidence: 0.59,
      status: "NEEDS_REVIEW",
      notes: "Simulated alt-art ambiguity from uploaded still image.",
      review: {
        suggestedMatch: "Iono 185/193",
        alternateMatches: ["Iono 237/091", "Iono 254/193"],
        reason: "Alternate art candidates require manual review.",
      },
    },
  ],
};

type CatalogLookupRow = {
  id: string;
};

type CatalogResolvedRow = {
  id: string;
  name: string;
  setName: string;
  cardNumber: string;
  rarity: string | null;
};

type ExistingCountRow = {
  count: number;
};

type CatalogTemplate = {
  id: string;
  name: string;
  setName: string;
  cardNumber: string;
  rarity: string | null;
};

export type CatalogRecognitionCard = CatalogTemplate & {
  externalSetId: string | null;
  imageLargeUrl: string | null;
  imageSmallUrl: string | null;
  imageHashFull: string | null;
  imageHashCandidates: string | null;
};

type ProcessMediaMetadata = {
  originalFileName: string;
  durationSeconds?: number;
  imageCount?: number;
  width?: number;
  height?: number;
  mimeType?: string;
  recognizedCards?: DetectionTemplate[];
};

async function listCatalogTemplates(): Promise<CatalogTemplate[]> {
  return queryRows<CatalogTemplate>(`
    SELECT id, name, setName, cardNumber, rarity
    FROM CatalogCard
    ORDER BY createdAt ASC;
  `);
}

export async function listCatalogRecognitionCards(): Promise<CatalogRecognitionCard[]> {
  return queryRows<CatalogRecognitionCard>(`
    SELECT
      CatalogCard.id,
      CatalogCard.name,
      CatalogCard.setName,
      CatalogCard.cardNumber,
      CatalogCard.rarity,
      CatalogSet.externalSetId,
      CatalogCard.imageLargeUrl,
      CatalogCard.imageSmallUrl,
      CatalogCard.imageHashFull,
      CatalogCard.imageHashCandidates
    FROM CatalogCard
    LEFT JOIN CatalogSet ON CatalogSet.id = CatalogCard.setId
    ORDER BY CatalogCard.createdAt ASC;
  `);
}

function normalizeLookupValue(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

function buildDynamicTemplates(
  kind: "video" | "images",
  metadata: ProcessMediaMetadata,
  catalog: CatalogTemplate[],
): DetectionTemplate[] {
  if (metadata.recognizedCards) {
    return metadata.recognizedCards;
  }

  const normalizedFileName = normalizeLookupValue(path.parse(metadata.originalFileName).name);
  const filenameMatches = catalog.filter((card) =>
    normalizeLookupValue(card.name)
      .split(" ")
      .every((token) => token.length > 1 && normalizedFileName.includes(token)),
  );

  const baseCards = (filenameMatches.length > 0 ? filenameMatches : catalog).slice(
    0,
    kind === "video"
      ? Math.max(1, Math.min(6, Math.floor((metadata.durationSeconds ?? 6) / 2)))
      : Math.max(1, Math.min(3, metadata.imageCount ?? 1)),
  );

  return baseCards.map((card, index) => {
    const shouldReview = filenameMatches.length === 0 && index === baseCards.length - 1;
    const metadataNote =
      kind === "video"
        ? `Derived from uploaded video (${metadata.durationSeconds ?? 0}s${metadata.mimeType ? ` · ${metadata.mimeType}` : ""}).`
        : `Derived from uploaded image${metadata.width && metadata.height ? ` (${metadata.width}x${metadata.height})` : ""}.`;

    return {
      cardName: card.name,
      setName: card.setName,
      cardNumber: card.cardNumber,
      rarity: card.rarity ?? "Unknown",
      confidence: filenameMatches.length > 0 ? 0.96 - index * 0.03 : shouldReview ? 0.62 : 0.88 - index * 0.04,
      status: shouldReview ? "NEEDS_REVIEW" : "MATCHED",
      notes: filenameMatches.length > 0 ? `Filename hint matched "${card.name}". ${metadataNote}` : metadataNote,
      review: shouldReview
        ? {
            suggestedMatch: `${card.name} ${card.cardNumber}`,
            alternateMatches: catalog
              .filter((entry) => entry.id !== card.id)
              .slice(0, 2)
              .map((entry) => `${entry.name} ${entry.cardNumber}`),
            reason: "Metadata-only intake still needs seller confirmation for at least one candidate.",
          }
        : undefined,
    };
  });
}

export async function processSqliteUpload(
  batchId: string,
  uploadId: string,
  kind: "video" | "images",
  metadata: ProcessMediaMetadata,
) {
  const safeBatchId = escapeSqliteString(batchId);
  const safeUploadId = escapeSqliteString(uploadId);

  await runStatement(`
    UPDATE Upload
    SET status = 'PROCESSING'
    WHERE id = '${safeUploadId}';
  `);

  const countRows = await queryRows<ExistingCountRow>(`
    SELECT COUNT(*) AS count
    FROM Detection
    WHERE batchId = '${safeBatchId}';
  `);

  let nextCardIndex = (countRows[0]?.count ?? 0) + 1;
  let reviewCountAdded = 0;
  const catalog = await listCatalogTemplates();
  const detectionTemplates =
    catalog.length > 0 ? buildDynamicTemplates(kind, metadata, catalog) : PROCESSING_TEMPLATES[kind];

  for (const template of detectionTemplates) {
    const cardRows = await queryRows<CatalogLookupRow>(`
      SELECT id
      FROM CatalogCard
      WHERE name = '${escapeSqliteString(template.cardName)}'
        AND setName = '${escapeSqliteString(template.setName)}'
        AND cardNumber = '${escapeSqliteString(template.cardNumber)}'
      LIMIT 1;
    `);

    const suggestedCardId = cardRows[0]?.id ?? null;
    const detectionId = `det-${crypto.randomUUID()}`;
    const sourceLabel =
      template.sourceLabel ?? `${kind === "video" ? "Card" : "Image"} ${String(nextCardIndex).padStart(3, "0")}`;

    await runStatement(`
      INSERT INTO Detection (
        id,
        batchId,
        uploadId,
        sourceLabel,
        suggestedCardId,
        cardName,
        setName,
        cardNumber,
        rarity,
        confidence,
        status,
        notes,
        titleOverride,
        priceOverride,
        quantityOverride,
        conditionOverride,
        excludeFromExport,
        createdAt,
        updatedAt
      ) VALUES (
        '${detectionId}',
        '${safeBatchId}',
        '${safeUploadId}',
        '${escapeSqliteString(sourceLabel)}',
        ${suggestedCardId ? `'${escapeSqliteString(suggestedCardId)}'` : "NULL"},
        '${escapeSqliteString(template.cardName)}',
        '${escapeSqliteString(template.setName)}',
        '${escapeSqliteString(template.cardNumber)}',
        '${escapeSqliteString(template.rarity)}',
        ${template.confidence},
        '${template.status}',
        ${template.notes ? `'${escapeSqliteString(template.notes)}'` : "NULL"},
        NULL,
        NULL,
        NULL,
        NULL,
        0,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
      );
    `);

    if (template.review) {
      reviewCountAdded += 1;
      const reviewId = `rev-${crypto.randomUUID()}`;
      await runStatement(`
        INSERT INTO ReviewItem (
          id,
          batchId,
          detectionId,
          suggestedMatch,
          alternateMatches,
          reason,
          state,
          createdAt,
          updatedAt
        ) VALUES (
          '${reviewId}',
          '${safeBatchId}',
          '${detectionId}',
          '${escapeSqliteString(template.review.suggestedMatch)}',
          '${escapeSqliteString(template.review.alternateMatches.join("||"))}',
          '${escapeSqliteString(template.review.reason)}',
          'OPEN',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
        );
      `);
    }

    nextCardIndex += 1;
  }

  await runStatement(`
    UPDATE Upload
    SET status = 'COMPLETE'
    WHERE id = '${safeUploadId}';
  `);

  await recalculateBatchState(safeBatchId);

  return {
    detectionsAdded: detectionTemplates.length,
    reviewCountAdded,
  };
}

async function recalculateBatchState(batchId: string) {
  const safeBatchId = escapeSqliteString(batchId);

  await runStatement(`
    UPDATE Batch
    SET
      itemCount = (SELECT COUNT(*) FROM Detection WHERE batchId = '${safeBatchId}'),
      reviewCount = (SELECT COUNT(*) FROM ReviewItem WHERE batchId = '${safeBatchId}' AND state = 'OPEN'),
      status = CASE
        WHEN (SELECT COUNT(*) FROM ReviewItem WHERE batchId = '${safeBatchId}' AND state = 'OPEN') > 0 THEN 'REVIEW'
        WHEN (SELECT COUNT(*) FROM Detection WHERE batchId = '${safeBatchId}') > 0 THEN 'READY'
        ELSE 'DRAFT'
      END,
      exportReady = CASE
        WHEN (SELECT COUNT(*) FROM ReviewItem WHERE batchId = '${safeBatchId}' AND state = 'OPEN') > 0 THEN 0
        WHEN (SELECT COUNT(*) FROM Detection WHERE batchId = '${safeBatchId}') > 0 THEN 1
        ELSE 0
      END,
      updatedAt = CURRENT_TIMESTAMP
    WHERE id = '${safeBatchId}';
  `);
}

export async function resolveReviewItem(
  batchId: string,
  reviewItemId: string,
  decision: "accept" | "dismiss",
  selectedMatch?: string,
) {
  const safeBatchId = escapeSqliteString(batchId);
  const safeReviewItemId = escapeSqliteString(reviewItemId);

  if (decision === "dismiss") {
    await runStatement(`
      UPDATE Detection
      SET
        status = 'REJECTED',
        updatedAt = CURRENT_TIMESTAMP
      WHERE id = (
        SELECT detectionId
        FROM ReviewItem
        WHERE id = '${safeReviewItemId}'
      );
    `);

    await runStatement(`
      UPDATE ReviewItem
      SET
        state = 'DISMISSED',
        resolvedAt = CURRENT_TIMESTAMP,
        updatedAt = CURRENT_TIMESTAMP
      WHERE id = '${safeReviewItemId}';
    `);

    await recalculateBatchState(safeBatchId);
    return;
  }

  const reviewRows = await queryRows<{
    detectionId: string;
    suggestedMatch: string;
  }>(`
    SELECT detectionId, suggestedMatch
    FROM ReviewItem
    WHERE id = '${safeReviewItemId}'
    LIMIT 1;
  `);

  const review = reviewRows[0];

  if (!review) {
    throw new Error("Review item not found.");
  }

  const resolvedMatch = (selectedMatch || review.suggestedMatch).trim();
  const lastSpaceIndex = resolvedMatch.lastIndexOf(" ");
  const selectedNumber = lastSpaceIndex > 0 ? resolvedMatch.slice(lastSpaceIndex + 1).trim() : "";
  const selectedName = lastSpaceIndex > 0 ? resolvedMatch.slice(0, lastSpaceIndex).trim() : resolvedMatch;

  const resolvedRows = await queryRows<CatalogResolvedRow>(`
    SELECT id, name, setName, cardNumber, rarity
    FROM CatalogCard
    WHERE name = '${escapeSqliteString(selectedName)}'
      AND cardNumber = '${escapeSqliteString(selectedNumber)}'
    LIMIT 1;
  `);

  const resolvedCard = resolvedRows[0];

  if (resolvedCard) {
    await runStatement(`
      UPDATE Detection
      SET
        suggestedCardId = '${escapeSqliteString(resolvedCard.id)}',
        cardName = '${escapeSqliteString(resolvedCard.name)}',
        setName = '${escapeSqliteString(resolvedCard.setName)}',
        cardNumber = '${escapeSqliteString(resolvedCard.cardNumber)}',
        rarity = ${resolvedCard.rarity ? `'${escapeSqliteString(resolvedCard.rarity)}'` : "NULL"},
        status = 'MATCHED',
        updatedAt = CURRENT_TIMESTAMP
      WHERE id = '${escapeSqliteString(review.detectionId)}';
    `);

    await runStatement(`
      UPDATE ReviewItem
      SET
        state = 'RESOLVED',
        resolvedCardId = '${escapeSqliteString(resolvedCard.id)}',
        resolvedAt = CURRENT_TIMESTAMP,
        updatedAt = CURRENT_TIMESTAMP
      WHERE id = '${safeReviewItemId}';
    `);
  } else {
    await runStatement(`
      UPDATE ReviewItem
      SET
        state = 'RESOLVED',
        resolvedAt = CURRENT_TIMESTAMP,
        updatedAt = CURRENT_TIMESTAMP
      WHERE id = '${safeReviewItemId}';
    `);
  }

  await recalculateBatchState(safeBatchId);
}

export async function getExportableBatchRows(batchId: string): Promise<ExportableRow[]> {
  const safeBatchId = escapeSqliteString(batchId);

  return queryRows<ExportableRow>(`
    SELECT
      Detection.id AS detectionId,
      Detection.sourceLabel,
      Detection.cardName,
      Detection.setName,
      COALESCE(ResolvedCard.setCode, CatalogCard.setCode) AS setCode,
      COALESCE(ResolvedSet.externalSetId, CatalogSet.externalSetId) AS externalSetId,
      Detection.cardNumber,
      Detection.rarity,
      COALESCE(ResolvedCard.imageLargeUrl, CatalogCard.imageLargeUrl) AS imageLargeUrl,
      COALESCE(ResolvedCard.imageSmallUrl, CatalogCard.imageSmallUrl) AS imageSmallUrl,
      Detection.titleOverride,
      Detection.priceOverride,
      Detection.quantityOverride,
      Detection.conditionOverride,
      Detection.excludeFromExport
    FROM Detection
    LEFT JOIN ReviewItem AS ResolvedReview
      ON ResolvedReview.detectionId = Detection.id
      AND ResolvedReview.state = 'RESOLVED'
    LEFT JOIN CatalogCard ON CatalogCard.id = Detection.suggestedCardId
    LEFT JOIN CatalogCard AS ResolvedCard ON ResolvedCard.id = ResolvedReview.resolvedCardId
    LEFT JOIN CatalogSet ON CatalogSet.id = CatalogCard.setId
    LEFT JOIN CatalogSet AS ResolvedSet ON ResolvedSet.id = ResolvedCard.setId
    WHERE Detection.batchId = '${safeBatchId}'
      AND Detection.excludeFromExport = 0
      AND Detection.status = 'MATCHED'
    ORDER BY Detection.createdAt ASC;
  `);
}

export async function createExportRun(batchId: string, format: string, status: string, filePath: string) {
  const id = `export-${crypto.randomUUID()}`;
  const safeBatchId = escapeSqliteString(batchId);
  const safeFormat = escapeSqliteString(format);
  const safeStatus = escapeSqliteString(status);
  const safeFilePath = escapeSqliteString(filePath);

  await runStatement(`
    INSERT INTO ExportRun (
      id,
      batchId,
      format,
      status,
      filePath,
      createdAt,
      updatedAt
    ) VALUES (
      '${id}',
      '${safeBatchId}',
      '${safeFormat}',
      '${safeStatus}',
      '${safeFilePath}',
      CURRENT_TIMESTAMP,
      CURRENT_TIMESTAMP
    );
  `);

  return id;
}

type UpdateListingSettingsInput = BatchListingSettings & {
  batchId: string;
};

export async function updateBatchListingSettings(input: UpdateListingSettingsInput) {
  const safeBatchId = escapeSqliteString(input.batchId);

  await runStatement(`
    UPDATE Batch
    SET
      location = '${escapeSqliteString(input.location)}',
      shippingType = '${escapeSqliteString(input.shippingType)}',
      shippingCost = '${escapeSqliteString(input.shippingCost)}',
      returnsAcceptedOption = '${escapeSqliteString(input.returnsAcceptedOption)}',
      returnsWithinOption = '${escapeSqliteString(input.returnsWithinOption)}',
      refundOption = '${escapeSqliteString(input.refundOption)}',
      shippingCostPaidByOption = '${escapeSqliteString(input.shippingCostPaidByOption)}',
      dispatchTimeMax = ${Number(input.dispatchTimeMax) || 3},
      cardConditionDescriptor = '${escapeSqliteString(input.cardConditionDescriptor)}',
      descriptionTemplate = '${escapeSqliteString(input.descriptionTemplate)}',
      updatedAt = CURRENT_TIMESTAMP
    WHERE id = '${safeBatchId}';
  `);
}

type UpdateDetectionOverridesInput = {
  batchId: string;
  detectionId: string;
  titleOverride: string;
  priceOverride: string;
  quantityOverride: string;
  conditionOverride: string;
  excludeFromExport: boolean;
};

export async function updateDetectionOverrides(input: UpdateDetectionOverridesInput) {
  const safeBatchId = escapeSqliteString(input.batchId);
  const safeDetectionId = escapeSqliteString(input.detectionId);
  const quantityValue = Number.parseInt(input.quantityOverride, 10);

  await runStatement(`
    UPDATE Detection
    SET
      titleOverride = ${input.titleOverride ? `'${escapeSqliteString(input.titleOverride)}'` : "NULL"},
      priceOverride = ${input.priceOverride ? `'${escapeSqliteString(input.priceOverride)}'` : "NULL"},
      quantityOverride = ${Number.isFinite(quantityValue) && quantityValue > 0 ? quantityValue : "NULL"},
      conditionOverride = ${input.conditionOverride ? `'${escapeSqliteString(input.conditionOverride)}'` : "NULL"},
      excludeFromExport = ${input.excludeFromExport ? 1 : 0},
      updatedAt = CURRENT_TIMESTAMP
    WHERE id = '${safeDetectionId}' AND batchId = '${safeBatchId}';
  `);

  await recalculateBatchState(safeBatchId);
}
