"use server";

import { revalidatePath } from "next/cache";
import { updateBatchListingSettings } from "@/lib/sqlite-repository";

function getStringValue(formData: FormData, key: string) {
  const value = formData.get(key);
  return typeof value === "string" ? value.trim() : "";
}

export async function saveListingSettingsAction(formData: FormData) {
  const batchId = getStringValue(formData, "batchId");

  if (!batchId) {
    throw new Error("Batch id is required.");
  }

  await updateBatchListingSettings({
    batchId,
    location: getStringValue(formData, "location") || "Toronto, Ontario",
    shippingType: getStringValue(formData, "shippingType") === "Free" ? "Free" : "Flat",
    shippingCost: getStringValue(formData, "shippingCost") || "1.99",
    returnsAcceptedOption:
      getStringValue(formData, "returnsAcceptedOption") === "ReturnsNotAccepted"
        ? "ReturnsNotAccepted"
        : "ReturnsAccepted",
    returnsWithinOption: getStringValue(formData, "returnsWithinOption") || "Days_30",
    refundOption: getStringValue(formData, "refundOption") || "MoneyBack",
    shippingCostPaidByOption:
      getStringValue(formData, "shippingCostPaidByOption") === "Seller" ? "Seller" : "Buyer",
    dispatchTimeMax: getStringValue(formData, "dispatchTimeMax") || "3",
    cardConditionDescriptor: getStringValue(formData, "cardConditionDescriptor") || "400010",
    descriptionTemplate:
      getStringValue(formData, "descriptionTemplate") ||
      "{card_name} from {set_name}. Card number: {card_number}. Rarity: {rarity}. Generated by TCG Listing Platform draft export.",
  });

  revalidatePath("/batches");
  revalidatePath(`/batches/${batchId}`);
}
